- name: Create Milestone JS
  uses: sv-tools/create-milestone-action@v1.4.0
  with:
    token: ${{ secrets.GITHUB_TOKEN }}
    title: Next
    description: Next Release, To be renamed with a proper semver.